167574995 Enable Social Login via Google
andela/ah-rambo-backend pull request #25
Opened 2019-08-06 05:35 UTC by Adekoreday

#### What does this PR do?
This PR enables the existing user to log in and new user  signup to the application via google
…

#### Description of Task proposed in this pull request?
- This PR uses the passportjs Google strategy to the codebase, which enables authenticating the user via google. The core implementation of this feature exists in the helper function google.js and it was integrated into our existing API for facebook authentication.

#### How should this be manually tested (Quality Assurance)?
 ```
npm run start: dev
open your browser and go to the following URL
http:locahost:5000/api/v1/auth/google
The user is redirected to the following URL automatically
http:localhost:5000/api/v1/auth/google/callback

   ```

#### What are the relevant pivotal tracker stories?
- [167574995] (https://www.pivotaltracker.com/story/show/167574995)

#### Any background context you want to add?
```
- npm install
-add the following .env variables
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URL=http://localhost:5000/api/v1/auth/google/callback
```
#### What I have learned working on this feature:
- I learnt how to authenticate user using passport

#### Screenshots: 
<img width="918" alt="Screenshot 2019-08-05 at 11 49 17 PM" src="https://user-images.githubusercontent.com/44194416/62513554-5d8eb100-b814-11e9-8dc8-bae61ab9e393.png">
<img width="1345" alt="Screenshot 2019-08-05 at 11 49 48 PM" src="https://user-images.githubusercontent.com/44194416/62513559-654e5580-b814-11e9-9d89-76e1d782df17.png">

2019-08-06 18:20 UTC, JuwonAbiola submitted a review, later dismissed

2019-08-06 18:55 UTC, chialuka submitted a review, later dismissed

2019-08-06 19:04 UTC, JuwonAbiola submitted a review, later dismissed

2019-08-06 22:04 UTC, henryade submitted a review, later dismissed

2019-08-06 23:21 UTC, dinobi commented on test/auth/facebook.test.js
> +  it('it should test route nock off the http request to fb', async () => {
`it should` pls fix this

2019-08-06 23:22 UTC, dinobi commented on test/auth/facebook.test.js
>    it('it mocks passport app', async () => {
and this

2019-08-06 23:22 UTC, dinobi commented on test/auth/facebook.test.js
>    it('it facebookLoginController', async () => {
and this

2019-08-06 23:23 UTC, dinobi commented on test/auth/facebook.test.js
> +  it('it test facebook helpers', async () => {
and this

2019-08-06 23:24 UTC, dinobi commented on test/auth/google.test.js
> +  context('when user successfully login', () => {
the use case for `context` here doesn't make sense

2019-08-06 23:25 UTC, dinobi commented on test/auth/google.test.js
> +    it('it  Logs in with google', async () => {
fix this

2019-08-06 23:25 UTC, dinobi commented on test/auth/google.test.js
> +    it('it test google strategy', async () => {
fix this

2019-08-06 23:26 UTC, dinobi requested changes
Please address all the comments
done thanks

2019-08-07 11:24 UTC, abdulfatai360 submitted a review, later dismissed

2019-08-07 11:29 UTC, Adekoreday commented on test/auth/facebook.test.js
>    it('it facebookLoginController', async () => {
done

2019-08-07 11:29 UTC, Adekoreday commented on test/auth/facebook.test.js
> +  it('it test facebook helpers', async () => {
done

2019-08-07 11:29 UTC, Adekoreday commented on test/auth/google.test.js
> +    it('it  Logs in with google', async () => {
done

2019-08-07 11:38 UTC, chialuka submitted a review, later dismissed

2019-08-07 13:35 UTC, henryade submitted a review, later dismissed

2019-08-07 15:28 UTC, dinobi approved these changes

2019-08-07 16:55 UTC, merged